// Global search data - aggregates all searchable content across the site

export type SearchResult = {
  title: string;
  description: string;
  href: string;
  category: string;
  keywords: string[];
};

export const searchableContent: SearchResult[] = [
  // Rendering Strategies
  {
    title: "Static Site Generation (SSG)",
    description: "Pre-render pages at build time for blazing fast delivery",
    href: "/ssg",
    category: "Rendering",
    keywords: ["ssg", "static", "build time", "getStaticProps", "generateStaticParams"],
  },
  {
    title: "Server-Side Rendering (SSR)",
    description: "Render pages on every request with fresh data",
    href: "/ssr",
    category: "Rendering",
    keywords: ["ssr", "server", "request", "getServerSideProps", "dynamic", "cookies", "headers"],
  },
  {
    title: "Incremental Static Regeneration (ISR)",
    description: "Static pages with background revalidation",
    href: "/isr",
    category: "Rendering",
    keywords: ["isr", "revalidate", "stale-while-revalidate", "cache"],
  },
  {
    title: "Client-Side Rendering (CSR)",
    description: "Fetch data in the browser after JS loads",
    href: "/csr",
    category: "Rendering",
    keywords: ["csr", "client", "useEffect", "useState", "browser", "fetch"],
  },

  // React Hooks
  {
    title: "useState Hook",
    description: "Manage component state with useState",
    href: "/hooks#useState",
    category: "React Hooks",
    keywords: ["useState", "state", "hook", "react"],
  },
  {
    title: "useEffect Hook",
    description: "Handle side effects and lifecycle in functional components",
    href: "/hooks#useEffect",
    category: "React Hooks",
    keywords: ["useEffect", "side effects", "lifecycle", "mount", "unmount", "cleanup"],
  },
  {
    title: "useContext Hook",
    description: "Access context values without prop drilling",
    href: "/hooks#useContext",
    category: "React Hooks",
    keywords: ["useContext", "context", "provider", "consumer"],
  },
  {
    title: "useReducer Hook",
    description: "Manage complex state with reducer pattern",
    href: "/hooks#useReducer",
    category: "React Hooks",
    keywords: ["useReducer", "reducer", "dispatch", "action"],
  },
  {
    title: "useMemo Hook",
    description: "Memoize expensive calculations",
    href: "/hooks#useMemo",
    category: "React Hooks",
    keywords: ["useMemo", "memoization", "performance", "optimization"],
  },
  {
    title: "useCallback Hook",
    description: "Memoize function references",
    href: "/hooks#useCallback",
    category: "React Hooks",
    keywords: ["useCallback", "memoization", "function", "performance"],
  },
  {
    title: "useRef Hook",
    description: "Access DOM elements and persist values",
    href: "/hooks#useRef",
    category: "React Hooks",
    keywords: ["useRef", "ref", "dom", "persist", "mutable"],
  },

  // Context API
  {
    title: "Context API",
    description: "Share state across components without prop drilling",
    href: "/context",
    category: "React State",
    keywords: ["context", "provider", "consumer", "prop drilling", "global state"],
  },

  // Array Methods
  {
    title: "Array.map()",
    description: "Transform array elements",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["map", "array", "transform", "iterate"],
  },
  {
    title: "Array.filter()",
    description: "Filter array elements based on condition",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["filter", "array", "condition", "select"],
  },
  {
    title: "Array.reduce()",
    description: "Reduce array to single value",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["reduce", "array", "accumulator", "aggregate"],
  },
  {
    title: "Array.forEach()",
    description: "Execute function for each array element",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["forEach", "array", "loop", "iterate"],
  },
  {
    title: "Array.find()",
    description: "Find first element matching condition",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["find", "array", "search", "first"],
  },
  {
    title: "Array.some() & Array.every()",
    description: "Test array elements against condition",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["some", "every", "array", "test", "condition"],
  },
  {
    title: "Array.sort()",
    description: "Sort array elements",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["sort", "array", "order", "compare"],
  },
  {
    title: "Array.slice() & Array.splice()",
    description: "Extract or modify array portions",
    href: "/inbuilt-methods#array",
    category: "Array Methods",
    keywords: ["slice", "splice", "array", "extract", "modify"],
  },

  // String Methods
  {
    title: "String.split()",
    description: "Split string into array",
    href: "/inbuilt-methods#string",
    category: "String Methods",
    keywords: ["split", "string", "array", "divide"],
  },
  {
    title: "String.substring() & String.slice()",
    description: "Extract part of string",
    href: "/inbuilt-methods#string",
    category: "String Methods",
    keywords: ["substring", "slice", "string", "extract"],
  },
  {
    title: "String.replace()",
    description: "Replace string content",
    href: "/inbuilt-methods#string",
    category: "String Methods",
    keywords: ["replace", "string", "substitute"],
  },
  {
    title: "String.trim()",
    description: "Remove whitespace from string ends",
    href: "/inbuilt-methods#string",
    category: "String Methods",
    keywords: ["trim", "string", "whitespace"],
  },
  {
    title: "String.toLowerCase() & String.toUpperCase()",
    description: "Convert string case",
    href: "/inbuilt-methods#string",
    category: "String Methods",
    keywords: ["toLowerCase", "toUpperCase", "string", "case"],
  },

  // Object Methods
  {
    title: "Object.keys()",
    description: "Get object property keys",
    href: "/inbuilt-methods#object",
    category: "Object Methods",
    keywords: ["keys", "object", "properties"],
  },
  {
    title: "Object.values()",
    description: "Get object property values",
    href: "/inbuilt-methods#object",
    category: "Object Methods",
    keywords: ["values", "object", "properties"],
  },
  {
    title: "Object.entries()",
    description: "Get object key-value pairs",
    href: "/inbuilt-methods#object",
    category: "Object Methods",
    keywords: ["entries", "object", "key-value", "pairs"],
  },
  {
    title: "Object.assign()",
    description: "Copy properties to target object",
    href: "/inbuilt-methods#object",
    category: "Object Methods",
    keywords: ["assign", "object", "copy", "merge"],
  },
  {
    title: "Object.freeze() & Object.seal()",
    description: "Make object immutable",
    href: "/inbuilt-methods#object",
    category: "Object Methods",
    keywords: ["freeze", "seal", "object", "immutable"],
  },

  // Promise Methods
  {
    title: "Promise.all()",
    description: "Wait for all promises to resolve",
    href: "/inbuilt-methods#promise",
    category: "Promise Methods",
    keywords: ["promise", "all", "async", "parallel"],
  },
  {
    title: "Promise.race()",
    description: "Wait for first promise to settle",
    href: "/inbuilt-methods#promise",
    category: "Promise Methods",
    keywords: ["promise", "race", "async", "first"],
  },
  {
    title: "Promise.allSettled()",
    description: "Wait for all promises to settle",
    href: "/inbuilt-methods#promise",
    category: "Promise Methods",
    keywords: ["promise", "allSettled", "async", "settle"],
  },

  // API Patterns
  {
    title: "Fetch API",
    description: "Native browser API for making HTTP requests",
    href: "/api#fetch",
    category: "API Patterns",
    keywords: ["fetch", "api", "http", "request", "ajax", "rest"],
  },
  {
    title: "Axios",
    description: "Popular HTTP client library with interceptors",
    href: "/api#axios",
    category: "API Patterns",
    keywords: ["axios", "api", "http", "request", "interceptor"],
  },
  {
    title: "GraphQL",
    description: "Query language for APIs",
    href: "/api#graphql",
    category: "API Patterns",
    keywords: ["graphql", "api", "query", "mutation", "apollo"],
  },
  {
    title: "WebSocket & Real-time",
    description: "Bi-directional real-time communication",
    href: "/api#websocket",
    category: "API Patterns",
    keywords: ["websocket", "realtime", "sse", "server-sent events", "live"],
  },
  {
    title: "React with Fetch",
    description: "Data fetching patterns in React components",
    href: "/api#react-fetch",
    category: "API Patterns",
    keywords: ["react", "fetch", "api", "useEffect", "loading"],
  },
  {
    title: "Custom Hooks for API",
    description: "Reusable API fetching hooks",
    href: "/api#custom-hooks",
    category: "API Patterns",
    keywords: ["custom hooks", "api", "react", "reusable"],
  },

  // Testing (Jest)
  {
    title: "Jest Testing Guide",
    description: "Test structure, matchers, mocking, and coverage with Jest",
    href: "/jest",
    category: "Testing",
    keywords: ["jest", "testing", "unit tests", "assertions", "mocking"],
  },
  {
    title: "Test Structure (AAA)",
    description: "Arrange-Act-Assert pattern for clear test cases",
    href: "/jest#test-structure",
    category: "Testing",
    keywords: ["jest", "aaa", "arrange act assert", "test structure"],
  },
  {
    title: "Jest Matchers",
    description: "Core assertion matchers like toBe, toEqual, and toThrow",
    href: "/jest#matchers",
    category: "Testing",
    keywords: ["jest", "matchers", "toBe", "toEqual", "assertions"],
  },
  {
    title: "Mock Functions & Spies",
    description: "Mock behavior, track calls, and spy on real functions",
    href: "/jest#mocking",
    category: "Testing",
    keywords: ["jest", "mock", "jest.fn", "spy", "spyOn", "mockResolvedValue"],
  },
  {
    title: "Module Mocking",
    description: "Replace module exports with controlled test doubles",
    href: "/jest#module-mocking",
    category: "Testing",
    keywords: ["jest", "module mocking", "jest.mock", "requireActual"],
  },
  {
    title: "API Mocking with MSW",
    description: "Intercept network requests with Mock Service Worker",
    href: "/jest#api-mocking",
    category: "Testing",
    keywords: ["jest", "msw", "api mocking", "mock service worker", "fetch"],
  },
  {
    title: "Async Testing",
    description: "Test promises, async/await, and rejected errors",
    href: "/jest#async-testing",
    category: "Testing",
    keywords: ["jest", "async", "await", "resolves", "rejects"],
  },
  {
    title: "Fake Timers",
    description: "Control setTimeout and setInterval with fake timers",
    href: "/jest#timers",
    category: "Testing",
    keywords: ["jest", "fake timers", "advanceTimersByTime", "setTimeout"],
  },
  {
    title: "Setup & Teardown",
    description: "Global and per-test setup with beforeEach and afterEach",
    href: "/jest#setup-teardown",
    category: "Testing",
    keywords: ["jest", "beforeEach", "afterEach", "setup", "teardown"],
  },
  {
    title: "Snapshot Testing",
    description: "Capture UI output with snapshots",
    href: "/jest#snapshots",
    category: "Testing",
    keywords: ["jest", "snapshots", "toMatchSnapshot", "ui"],
  },
  {
    title: "Code Coverage",
    description: "Generate coverage reports and enforce thresholds",
    href: "/jest#coverage",
    category: "Testing",
    keywords: ["jest", "coverage", "thresholds", "report"],
  },

  // JavaScript Core Concepts
  {
    title: "Closures",
    description: "Functions that remember their lexical scope",
    href: "/js#closures",
    category: "JavaScript Core",
    keywords: ["closure", "scope", "lexical", "function"],
  },
  {
    title: "Event Loop",
    description: "How JavaScript handles async operations",
    href: "/js#event-loop",
    category: "JavaScript Core",
    keywords: ["event loop", "async", "callback", "microtask", "macrotask"],
  },
  {
    title: "Promises",
    description: "Handle asynchronous operations",
    href: "/js#promises",
    category: "JavaScript Core",
    keywords: ["promise", "async", "then", "catch", "resolve", "reject"],
  },
  {
    title: "async/await",
    description: "Modern syntax for async code",
    href: "/js#async-await",
    category: "JavaScript Core",
    keywords: ["async", "await", "promise", "asynchronous"],
  },
  {
    title: "Prototype & Inheritance",
    description: "JavaScript's prototypal inheritance",
    href: "/js#prototype",
    category: "JavaScript Core",
    keywords: ["prototype", "inheritance", "proto", "constructor"],
  },
  {
    title: "this keyword",
    description: "Context binding in JavaScript",
    href: "/js#this",
    category: "JavaScript Core",
    keywords: ["this", "bind", "call", "apply", "context"],
  },
  {
    title: "Hoisting",
    description: "Variable and function declaration behavior",
    href: "/js#hoisting",
    category: "JavaScript Core",
    keywords: ["hoisting", "var", "let", "const", "tdz"],
  },

  // Next.js Features
  {
    title: "App Router",
    description: "Next.js 13+ file-based routing system",
    href: "/nextjs#app-router",
    category: "Next.js",
    keywords: ["app router", "nextjs", "routing", "file-based"],
  },
  {
    title: "Server Components",
    description: "React components that render on the server",
    href: "/nextjs#server-components",
    category: "Next.js",
    keywords: ["server components", "rsc", "nextjs", "streaming"],
  },
  {
    title: "Middleware",
    description: "Run code before request completes",
    href: "/nextjs#middleware",
    category: "Next.js",
    keywords: ["middleware", "nextjs", "routing", "authentication"],
  },
  {
    title: "Image Optimization",
    description: "Automatic image optimization with next/image",
    href: "/nextjs#image",
    category: "Next.js",
    keywords: ["image", "optimization", "nextjs", "lazy loading"],
  },
  {
    title: "getStaticProps",
    description: "Pages Router SSG - fetch data at build time for static generation",
    href: "/nextjs#get-static-props",
    category: "Next.js",
    keywords: ["getStaticProps", "ssg", "static", "build time", "pages router", "isr", "revalidate", "static site generation"],
  },
  {
    title: "getServerSideProps",
    description: "Pages Router SSR - fetch data on every request for dynamic content",
    href: "/nextjs#get-server-side-props",
    category: "Next.js",
    keywords: ["getServerSideProps", "ssr", "server side rendering", "pages router", "dynamic", "request", "cookies", "auth"],
  },
  {
    title: "getStaticPaths",
    description: "Define dynamic routes to pre-render with getStaticProps",
    href: "/nextjs#get-static-paths",
    category: "Next.js",
    keywords: ["getStaticPaths", "dynamic routes", "pages router", "paths", "fallback", "static generation", "params"],
  },
  {
    title: "ISR (Incremental Static Regeneration)",
    description: "Pages Router ISR - static pages with background revalidation",
    href: "/nextjs#pages-isr-revalidate",
    category: "Next.js",
    keywords: ["isr", "incremental static regeneration", "revalidate", "pages router", "stale-while-revalidate", "on-demand"],
  },
  {
    title: "Build Process",
    description: "Understanding npm run build: compilation, static generation, and why console.logs appear during build",
    href: "/nextjs#build-process",
    category: "Next.js",
    keywords: ["build", "npm run build", "static generation", "build time", "compilation", "optimization", "pre-render"],
  },

  // Playground
  {
    title: "Code Playground",
    description: "Interactive code editor for JavaScript, TypeScript, and React",
    href: "/playground",
    category: "Tools",
    keywords: ["playground", "code", "editor", "javascript", "typescript", "react", "repl"],
  },

  // Accessibility
  {
    title: "Web Accessibility (A11y)",
    description: "Complete guide to web accessibility, WCAG, and inclusive design",
    href: "/accessibility",
    category: "Accessibility",
    keywords: ["accessibility", "a11y", "wcag", "inclusive", "disability", "ada", "section 508"],
  },
  {
    title: "What is Accessibility",
    description: "Understanding web accessibility and POUR principles",
    href: "/accessibility#what-is-accessibility",
    category: "Accessibility",
    keywords: ["accessibility", "what", "definition", "pour", "perceivable", "operable", "understandable", "robust"],
  },
  {
    title: "Why Accessibility Matters",
    description: "Legal compliance, business benefits, and ethical responsibility",
    href: "/accessibility#why-accessibility",
    category: "Accessibility",
    keywords: ["why", "importance", "ada", "wcag", "legal", "compliance", "seo", "business"],
  },
  {
    title: "Semantic HTML",
    description: "Using meaningful HTML elements for accessibility",
    href: "/accessibility#semantic-html",
    category: "Accessibility",
    keywords: ["semantic", "html", "header", "nav", "main", "article", "section", "footer"],
  },
  {
    title: "ARIA - Accessible Rich Internet Applications",
    description: "ARIA roles, states, and properties for complex UI components",
    href: "/accessibility#aria",
    category: "Accessibility",
    keywords: ["aria", "roles", "states", "properties", "aria-label", "aria-labelledby", "aria-describedby", "aria-live", "aria-hidden"],
  },
  {
    title: "Screen Readers",
    description: "Understanding screen readers and assistive technologies",
    href: "/accessibility#screen-readers",
    category: "Accessibility",
    keywords: ["screen reader", "nvda", "jaws", "voiceover", "talkback", "narrator", "assistive technology", "sr-only"],
  },
  {
    title: "Keyboard Navigation",
    description: "Keyboard accessibility and focus management",
    href: "/accessibility#keyboard-navigation",
    category: "Accessibility",
    keywords: ["keyboard", "navigation", "focus", "tab", "tabindex", "focus trap", "skip links"],
  },
  {
    title: "Images & Alt Text",
    description: "Writing effective alternative text for images",
    href: "/accessibility#images-alt-text",
    category: "Accessibility",
    keywords: ["images", "alt text", "alternative text", "decorative", "informative", "functional"],
  },
  {
    title: "Accessible Forms",
    description: "Creating accessible forms with labels and error handling",
    href: "/accessibility#forms-accessibility",
    category: "Accessibility",
    keywords: ["forms", "labels", "input", "validation", "errors", "fieldset", "legend", "aria-invalid", "aria-required"],
  },
  {
    title: "Color & Contrast",
    description: "Meeting WCAG contrast requirements and color accessibility",
    href: "/accessibility#color-contrast",
    category: "Accessibility",
    keywords: ["color", "contrast", "wcag", "ratio", "color blindness", "low vision"],
  },
  {
    title: "Responsive Accessibility",
    description: "Mobile accessibility, touch targets, and viewport settings",
    href: "/accessibility#responsive-accessibility",
    category: "Accessibility",
    keywords: ["mobile", "responsive", "touch targets", "viewport", "zoom", "orientation"],
  },
  {
    title: "Accessibility Testing Tools",
    description: "Tools and resources for testing web accessibility",
    href: "/accessibility#testing-tools",
    category: "Accessibility",
    keywords: ["testing", "tools", "axe", "wave", "lighthouse", "devtools", "jest-axe", "cypress"],
  },
  {
    title: "Accessibility Checklist",
    description: "Essential accessibility checklist for web developers",
    href: "/accessibility#checklist",
    category: "Accessibility",
    keywords: ["checklist", "reference", "guide", "quick reference", "essentials"],
  },
  {
    title: "Accessible Component Patterns",
    description: "Common accessible component patterns and implementations",
    href: "/accessibility#common-patterns",
    category: "Accessibility",
    keywords: ["patterns", "components", "button", "modal", "tabs", "dropdown", "menu"],
  },

  // Git Commands
  {
    title: "git init",
    description: "Initialize a new Git repository",
    href: "/git#init",
    category: "Git",
    keywords: ["git", "init", "initialize", "repository", "setup"],
  },
  {
    title: "git clone",
    description: "Clone a remote repository to your local machine",
    href: "/git#clone",
    category: "Git",
    keywords: ["git", "clone", "copy", "repository", "download"],
  },
  {
    title: "git config",
    description: "Configure Git settings globally or locally",
    href: "/git#config",
    category: "Git",
    keywords: ["git", "config", "settings", "user", "email", "configuration"],
  },
  {
    title: "git status",
    description: "Show working tree status and staged changes",
    href: "/git#status",
    category: "Git",
    keywords: ["git", "status", "changes", "staged", "modified"],
  },
  {
    title: "git add",
    description: "Stage changes for the next commit",
    href: "/git#add",
    category: "Git",
    keywords: ["git", "add", "stage", "staging", "index"],
  },
  {
    title: "git commit",
    description: "Record staged changes to the repository",
    href: "/git#commit",
    category: "Git",
    keywords: ["git", "commit", "save", "snapshot", "message"],
  },
  {
    title: "git diff",
    description: "Show changes between commits, branches, or working tree",
    href: "/git#diff",
    category: "Git",
    keywords: ["git", "diff", "changes", "differences", "compare"],
  },
  {
    title: "git branch",
    description: "List, create, or delete branches",
    href: "/git#branch",
    category: "Git",
    keywords: ["git", "branch", "branches", "create", "delete", "list"],
  },
  {
    title: "git checkout",
    description: "Switch branches or restore files",
    href: "/git#checkout",
    category: "Git",
    keywords: ["git", "checkout", "switch", "branch", "restore"],
  },
  {
    title: "git switch",
    description: "Modern command to switch branches (Git 2.23+)",
    href: "/git#switch",
    category: "Git",
    keywords: ["git", "switch", "branch", "change", "modern"],
  },
  {
    title: "git merge",
    description: "Merge changes from another branch",
    href: "/git#merge",
    category: "Git",
    keywords: ["git", "merge", "integrate", "combine", "branches"],
  },
  {
    title: "git rebase",
    description: "Reapply commits on top of another base",
    href: "/git#rebase",
    category: "Git",
    keywords: ["git", "rebase", "linear", "history", "rewrite"],
  },
  {
    title: "git cherry-pick",
    description: "Apply specific commit from one branch to another",
    href: "/git#cherry-pick",
    category: "Git",
    keywords: ["git", "cherry-pick", "commit", "apply", "selective"],
  },
  {
    title: "git remote",
    description: "Manage remote repository connections",
    href: "/git#remote",
    category: "Git",
    keywords: ["git", "remote", "origin", "upstream", "connection"],
  },
  {
    title: "git fetch",
    description: "Download objects and refs from remote repository",
    href: "/git#fetch",
    category: "Git",
    keywords: ["git", "fetch", "download", "remote", "sync"],
  },
  {
    title: "git pull",
    description: "Fetch from remote and integrate into current branch",
    href: "/git#pull",
    category: "Git",
    keywords: ["git", "pull", "fetch", "merge", "update"],
  },
  {
    title: "git push",
    description: "Upload local commits to remote repository",
    href: "/git#push",
    category: "Git",
    keywords: ["git", "push", "upload", "remote", "publish"],
  },
  {
    title: "git log",
    description: "Show commit history and logs",
    href: "/git#log",
    category: "Git",
    keywords: ["git", "log", "history", "commits", "timeline"],
  },
  {
    title: "git show",
    description: "Show details of Git objects and commits",
    href: "/git#show",
    category: "Git",
    keywords: ["git", "show", "details", "commit", "inspect"],
  },
  {
    title: "git blame",
    description: "Show who modified each line of a file",
    href: "/git#blame",
    category: "Git",
    keywords: ["git", "blame", "author", "history", "line"],
  },
  {
    title: "git reflog",
    description: "Show reference log to recover lost commits",
    href: "/git#reflog",
    category: "Git",
    keywords: ["git", "reflog", "recover", "lost", "commits", "history"],
  },
  {
    title: "git restore",
    description: "Restore files to specific state (Git 2.23+)",
    href: "/git#restore",
    category: "Git",
    keywords: ["git", "restore", "undo", "discard", "file"],
  },
  {
    title: "git reset",
    description: "Reset current HEAD to specified state",
    href: "/git#reset",
    category: "Git",
    keywords: ["git", "reset", "undo", "soft", "hard", "mixed"],
  },
  {
    title: "git revert",
    description: "Create new commit that undoes previous commit",
    href: "/git#revert",
    category: "Git",
    keywords: ["git", "revert", "undo", "rollback", "safe"],
  },
  {
    title: "git clean",
    description: "Remove untracked files from working tree",
    href: "/git#clean",
    category: "Git",
    keywords: ["git", "clean", "remove", "untracked", "files"],
  },
  {
    title: "git stash",
    description: "Temporarily save uncommitted changes",
    href: "/git#stash",
    category: "Git",
    keywords: ["git", "stash", "save", "temporary", "wip"],
  },
  {
    title: "git tag",
    description: "Create, list, and verify tags for releases",
    href: "/git#tag",
    category: "Git",
    keywords: ["git", "tag", "release", "version", "annotated"],
  },
  {
    title: "git bisect",
    description: "Binary search to find bug-introducing commit",
    href: "/git#bisect",
    category: "Git",
    keywords: ["git", "bisect", "bug", "find", "binary search", "debug"],
  },
  {
    title: "git submodule",
    description: "Manage external repositories within your repository",
    href: "/git#submodule",
    category: "Git",
    keywords: ["git", "submodule", "dependencies", "external", "nested"],
  },
  {
    title: "git worktree",
    description: "Manage multiple working trees for same repository",
    href: "/git#worktree",
    category: "Git",
    keywords: ["git", "worktree", "multiple", "branches", "parallel"],
  },
  {
    title: "git grep",
    description: "Search for patterns in tracked files",
    href: "/git#grep",
    category: "Git",
    keywords: ["git", "grep", "search", "find", "pattern"],
  },
  {
    title: "git format-patch",
    description: "Generate patch files from commits for email-based workflows",
    href: "/git#format-patch",
    category: "Git",
    keywords: ["git", "format-patch", "patch", "email", "diff", "export"],
  },
  {
    title: "git apply",
    description: "Apply a patch file to working tree without committing",
    href: "/git#apply",
    category: "Git",
    keywords: ["git", "apply", "patch", "diff", "import"],
  },
  {
    title: "git am",
    description: "Apply patches from mailbox with commits and authorship",
    href: "/git#am",
    category: "Git",
    keywords: ["git", "am", "apply", "mailbox", "patch", "email"],
  },
  {
    title: ".gitignore Operations",
    description: "Manage ignored files and debug .gitignore rules",
    href: "/git#gitignore",
    category: "Git",
    keywords: ["gitignore", "ignore", "check-ignore", "untrack", "cached"],
  },
  {
    title: "Git Aliases",
    description: "Create shortcuts for frequently used Git commands",
    href: "/git#aliases",
    category: "Git",
    keywords: ["git", "alias", "shortcuts", "config", "custom", "commands"],
  },
  {
    title: "Interactive Rebase",
    description: "Advanced rebase operations: squash, fixup, reword, edit, drop commits",
    href: "/git#interactive-rebase",
    category: "Git",
    keywords: ["git", "rebase", "interactive", "squash", "fixup", "reword", "autosquash"],
  },
  {
    title: "Git Workflows",
    description: "Git Flow, Trunk-Based Development, Feature Branch, Forking workflows",
    href: "/git#workflows",
    category: "Git",
    keywords: ["git", "workflow", "gitflow", "trunk", "feature branch", "forking", "strategy"],
  },
  {
    title: "Merge Strategies",
    description: "Fast-forward, no-ff, squash merge strategies explained",
    href: "/git#merge-strategies",
    category: "Git",
    keywords: ["git", "merge", "strategy", "fast-forward", "no-ff", "squash", "rebase"],
  },

  // TypeScript Concepts
  {
    title: "Basic Types",
    description: "TypeScript primitive types: string, number, boolean, arrays, tuples",
    href: "/ts#basic-types",
    category: "TypeScript",
    keywords: ["typescript", "types", "primitive", "string", "number", "boolean", "array", "tuple", "any"],
  },
  {
    title: "Interfaces",
    description: "Define object shapes with optional and readonly properties",
    href: "/ts#interfaces",
    category: "TypeScript",
    keywords: ["typescript", "interface", "object", "shape", "optional", "readonly", "extends"],
  },
  {
    title: "Type Aliases",
    description: "Create custom types with unions, intersections, and primitives",
    href: "/ts#type-aliases",
    category: "TypeScript",
    keywords: ["typescript", "type", "alias", "union", "intersection", "custom"],
  },
  {
    title: "Generics",
    description: "Write reusable, type-safe code with generic type parameters",
    href: "/ts#generics",
    category: "TypeScript",
    keywords: ["typescript", "generics", "type parameters", "reusable", "constraints", "T"],
  },
  {
    title: "Union & Intersection Types",
    description: "Combine types with unions (|) and intersections (&)",
    href: "/ts#union-intersection",
    category: "TypeScript",
    keywords: ["typescript", "union", "intersection", "discriminated", "tagged", "combine"],
  },
  {
    title: "Type Guards",
    description: "Narrow types with typeof, instanceof, in, and custom guards",
    href: "/ts#type-guards",
    category: "TypeScript",
    keywords: ["typescript", "type guard", "narrowing", "typeof", "instanceof", "is", "predicate"],
  },
  {
    title: "Utility Types",
    description: "Built-in type transformations: Partial, Required, Pick, Omit, Record",
    href: "/ts#utility-types",
    category: "TypeScript",
    keywords: ["typescript", "utility", "partial", "required", "pick", "omit", "record", "readonly", "returntype"],
  },
  {
    title: "Enums",
    description: "Define named constants with numeric and string enums",
    href: "/ts#enums",
    category: "TypeScript",
    keywords: ["typescript", "enum", "constants", "numeric", "string", "const enum"],
  },
  {
    title: "Literal Types",
    description: "Exact values as types with string, numeric, and template literals",
    href: "/ts#literal-types",
    category: "TypeScript",
    keywords: ["typescript", "literal", "exact", "string literal", "template literal", "const"],
  },
  {
    title: "never & unknown",
    description: "Type-safe handling of impossible and arbitrary values",
    href: "/ts#never-unknown",
    category: "TypeScript",
    keywords: ["typescript", "never", "unknown", "exhaustive", "type safe", "any"],
  },
  {
    title: "Mapped Types",
    description: "Transform object properties with mapped type operations",
    href: "/ts#mapped-types",
    category: "TypeScript",
    keywords: ["typescript", "mapped types", "keyof", "transform", "loop", "properties"],
  },
  {
    title: "Conditional Types",
    description: "Type-level conditionals with extends and infer",
    href: "/ts#conditional-types",
    category: "TypeScript",
    keywords: ["typescript", "conditional", "extends", "infer", "ternary", "distributive"],
  },
  {
    title: "Decorators",
    description: "Annotate and modify classes, methods, and properties",
    href: "/ts#decorators",
    category: "TypeScript",
    keywords: ["typescript", "decorator", "annotation", "class", "method", "property", "experimental"],
  },
  {
    title: "Modules & Namespaces",
    description: "ES6 modules and TypeScript namespaces for code organization",
    href: "/ts#modules-namespaces",
    category: "TypeScript",
    keywords: ["typescript", "module", "import", "export", "namespace", "esm"],
  },
  {
    title: "Type Assertions",
    description: "Tell TypeScript to treat values as specific types with 'as' syntax",
    href: "/ts#type-assertions",
    category: "TypeScript",
    keywords: ["typescript", "assertion", "as", "cast", "non-null", "const assertion"],
  },
  {
    title: "Classes & Access Modifiers",
    description: "TypeScript classes with public, private, protected, and readonly",
    href: "/ts#classes",
    category: "TypeScript",
    keywords: ["typescript", "class", "public", "private", "protected", "readonly", "abstract"],
  },
  {
    title: "Declaration Files (.d.ts)",
    description: "Type definitions for JavaScript libraries and ambient declarations",
    href: "/ts#declaration-files",
    category: "TypeScript",
    keywords: ["typescript", "declaration", "d.ts", "types", "ambient", "declare", "definitelytyped"],
  },
  {
    title: "tsconfig.json",
    description: "TypeScript compiler configuration and project setup",
    href: "/ts#tsconfig",
    category: "TypeScript",
    keywords: ["typescript", "tsconfig", "config", "compiler", "strict", "target", "module"],
  },
  {
    title: "React with TypeScript",
    description: "Type React components, props, state, events, and hooks",
    href: "/ts#react-with-ts",
    category: "TypeScript",
    keywords: ["typescript", "react", "props", "component", "hooks", "events", "jsx"],
  },
  {
    title: "TypeScript Best Practices",
    description: "Write maintainable TS: prefer inference, avoid any, use const assertions",
    href: "/ts#best-practices",
    category: "TypeScript",
    keywords: ["typescript", "best practices", "patterns", "tips", "inference", "branded types"],
  },

  // State Management (missing entries)
  {
    title: "Redux",
    description: "Predictable state container with actions, reducers, and middleware",
    href: "/state#redux",
    category: "React State",
    keywords: ["redux", "state management", "actions", "reducers", "store", "middleware", "redux toolkit"],
  },
  {
    title: "Zustand",
    description: "Lightweight state management with hooks, no providers needed",
    href: "/state#zustand",
    category: "React State",
    keywords: ["zustand", "state management", "hooks", "simple", "no provider", "lightweight"],
  },
  {
    title: "Recoil",
    description: "Facebook's state management with atoms and selectors",
    href: "/state#recoil",
    category: "React State",
    keywords: ["recoil", "state management", "atoms", "selectors", "facebook", "meta"],
  },
  {
    title: "Jotai",
    description: "Primitive and flexible atomic state management",
    href: "/state#jotai",
    category: "React State",
    keywords: ["jotai", "state management", "atoms", "atomic", "primitive"],
  },
  {
    title: "MobX",
    description: "Reactive state management with observables and computed values",
    href: "/state#mobx",
    category: "React State",
    keywords: ["mobx", "state management", "observable", "reactive", "computed", "action"],
  },

  // Advanced Topics
  {
    title: "AI Integration with Vercel AI SDK",
    description: "Build AI-powered apps with streaming, function calling, and RAG patterns",
    href: "/ai-integration",
    category: "Advanced",
    keywords: ["ai", "openai", "vercel ai sdk", "chatgpt", "streaming", "function calling", "tools", "rag", "embeddings", "llm"],
  },
  {
    title: "AI Streaming Responses",
    description: "Real-time AI responses with useChat hook and streaming text",
    href: "/ai-integration#streaming",
    category: "Advanced",
    keywords: ["ai", "streaming", "useChat", "real-time", "chatgpt-like", "vercel", "openai"],
  },
  {
    title: "AI Function Calling / Tools",
    description: "Give AI access to external functions and APIs",
    href: "/ai-integration#tools",
    category: "Advanced",
    keywords: ["ai", "function calling", "tools", "weather", "calculator", "database", "zod"],
  },
  {
    title: "RAG Pattern (Retrieval-Augmented Generation)",
    description: "AI with custom knowledge base using embeddings and vector search",
    href: "/ai-integration#rag",
    category: "Advanced",
    keywords: ["rag", "embeddings", "vector search", "ai", "knowledge base", "pinecone", "supabase"],
  },
  {
    title: "API Patterns & Best Practices",
    description: "Axios interceptors, service layer, custom hooks, and HOCs",
    href: "/api-patterns",
    category: "Advanced",
    keywords: ["api", "axios", "interceptors", "service layer", "hooks", "hoc", "patterns"],
  },
  {
    title: "Axios Interceptors",
    description: "Request/response interceptors for auth, logging, and error handling",
    href: "/api-patterns#interceptors",
    category: "Advanced",
    keywords: ["axios", "interceptors", "auth", "token refresh", "middleware", "logging"],
  },
  {
    title: "API Service Layer",
    description: "Organize API calls with service layer pattern - CRUD operations",
    href: "/api-patterns#service-layer",
    category: "Advanced",
    keywords: ["service layer", "api", "crud", "read", "write", "axios", "organization"],
  },
  {
    title: "Custom API Hooks",
    description: "Reusable hooks for data fetching with loading and error states",
    href: "/api-patterns#custom-hooks",
    category: "Advanced",
    keywords: ["custom hooks", "data fetching", "useApi", "loading", "error handling", "react"],
  },
  {
    title: "Higher-Order Components (HOC)",
    description: "HOC pattern for API protection and data fetching",
    href: "/api-patterns#hoc",
    category: "Advanced",
    keywords: ["hoc", "higher-order component", "withAuth", "withData", "api", "protection"],
  },
  {
    title: "JWT Authentication End-to-End",
    description: "Complete JWT auth flow with tokens, refresh, and protected routes",
    href: "/jwt-auth",
    category: "Advanced",
    keywords: ["jwt", "authentication", "auth", "token", "refresh token", "login", "security"],
  },
  {
    title: "JWT Token Generation",
    description: "Generate and verify JWT access and refresh tokens",
    href: "/jwt-auth#backend-setup",
    category: "Advanced",
    keywords: ["jwt", "token", "generate", "verify", "jsonwebtoken", "access token", "refresh token"],
  },
  {
    title: "JWT Login & Token Storage",
    description: "Login endpoint with token generation and httpOnly cookies",
    href: "/jwt-auth#login-route",
    category: "Advanced",
    keywords: ["jwt", "login", "authentication", "cookies", "httpOnly", "bcrypt", "password"],
  },
  {
    title: "JWT Token Refresh",
    description: "Auto-refresh expired tokens without re-login",
    href: "/jwt-auth#refresh-route",
    category: "Advanced",
    keywords: ["jwt", "refresh token", "auto-refresh", "token expiry", "authentication"],
  },
  {
    title: "Protected Routes & Middleware",
    description: "Protect API routes with JWT verification middleware",
    href: "/jwt-auth#middleware",
    category: "Advanced",
    keywords: ["jwt", "protected routes", "middleware", "authorization", "security", "next.js"],
  },
  {
    title: "Auth Context & Client-Side Auth",
    description: "React context for authentication state and token management",
    href: "/jwt-auth#client-side",
    category: "Advanced",
    keywords: ["auth context", "react context", "useAuth", "login", "logout", "client-side"],
  },
];

export function searchContent(query: string): SearchResult[] {
  if (!query.trim()) return [];

  const lowerQuery = query.toLowerCase();
  
  return searchableContent.filter((item) => {
    return (
      item.title.toLowerCase().includes(lowerQuery) ||
      item.description.toLowerCase().includes(lowerQuery) ||
      item.category.toLowerCase().includes(lowerQuery) ||
      item.keywords.some((keyword) => keyword.toLowerCase().includes(lowerQuery))
    );
  });
}
